package advisories

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/mlw157/GoScan/internal/models"
	"io"
	"net/http"
	"strconv"
	"strings"
)

type GitHubAdvisoryService struct {
	BaseURL    string
	HTTPClient *http.Client
}

// Response struct generated by https://mholt.github.io/json-to-go/
type Response struct {
	Severity        string `json:"severity"`
	CVE             string `json:"cve-id"`
	Summary         string `json:"summary"`
	Description     string `json:"description"`
	URL             string `json:"url"`
	Vulnerabilities []struct {
		Package struct {
			Name string `json:"name"`
		} `json:"package"`
		VulnerableVersionRange string `json:"vulnerable_version_range"`
	} `json:"vulnerabilities"`
	References []string `json:"references"`
}

func NewGitHubAdvisoryService() *GitHubAdvisoryService {
	return &GitHubAdvisoryService{
		BaseURL:    "https://api.github.com/advisories",
		HTTPClient: &http.Client{},
	}
}

func (s *GitHubAdvisoryService) FetchVulnerabilities(dependencies []models.Dependency) ([]models.Vulnerability, error) {
	// todo fix pagination (if dependencies len() exceeds 100)
	affectsParam := buildAffectsParam(dependencies)
	dependenciesLength := strconv.Itoa(len(dependencies))

	requestURL := s.BaseURL + "?affects=" + affectsParam + "&ecosystem=" + dependencies[0].Language + "&per_page=" + dependenciesLength

	resp, err := s.HTTPClient.Get(requestURL)

	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, errors.New("failed to fetch vulnerabilities" + resp.Status)
	}

	vulnerabilities, err := s.ParseResponse(resp.Body, dependencies)
	if err != nil {
		return nil, err
	}

	return vulnerabilities, nil
}

// todo
func (s *GitHubAdvisoryService) ParseResponse(body io.Reader, dependencies []models.Dependency) ([]models.Vulnerability, error) {
	var vulnerabilities []models.Vulnerability

	fmt.Print(body)

	bodyBytes, err := io.ReadAll(body)
	if err != nil {
		return nil, err
	}

	var responses []Response
	if err := json.Unmarshal(bodyBytes, &responses); err != nil {
		return nil, err
	}

	// todo parse all responses
	for _, res := range responses {
		fmt.Print(res)
	}
	return vulnerabilities, nil

}

// buildAffectsParam api.github.com/advisories parameter "affects" accepts a string of dependencies with versions
func buildAffectsParam(dependencies []models.Dependency) string {
	dependencyList := ""
	for _, dependency := range dependencies {
		dependencyList += dependency.Name + "@" + dependency.Version + ", "
	}
	return strings.Trim(dependencyList, ", ")
}
